import Head from 'next/head';

import Disk from '@/components/Disk';

const Home = () => {
  return (
    <>
      <Head>
        <title>Cloud storage</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Disk />
    </>
  );
};

export default Home;
